# Generated by Django 4.1.7 on 2023-05-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250)),
                ('floor', models.IntegerField(blank=True)),
                ('floor_amount', models.IntegerField(blank=True, default=0)),
                ('rooms', models.CharField(blank=True, max_length=100)),
                ('metres', models.FloatField(blank=True)),
                ('kitchen', models.IntegerField(blank=True, default=0)),
                ('repair', models.CharField(blank=True, max_length=30)),
                ('metro', models.CharField(blank=True, max_length=30)),
                ('time_to_metro', models.IntegerField(blank=True, default=0)),
                ('year_house', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
